- set_fact: dir={{ dockerfile_directory }}/java

- file: path={{ dir }} state=directory owner={{ os_admin_user }} group={{ os_admin_group }} mode=755
  become: yes

- template: src={{ item }}.j2 dest={{ dir }}/{{ item }} owner={{ os_admin_user }} group={{ os_admin_group }} mode=644
  with_items:
    - Dockerfile
  become: yes

- command: docker build -t {{ docker_java }} .
  args:
    chdir: "{{ dir }}"
  become: yes
