FROM centos:centos7.1.1503

RUN yum -y install wget

RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
         http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.rpm

RUN yum -y install jdk-8u77-linux-x64.rpm
